# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJW9T9ij9h3wZ2IAcbgCJyCrctiXbXzJ
"""

a=[1,2,3,'abc',4,5,7,8]
print(a[5])

b=['anita','lakshita','nikita','ishita']
print(b[-2])

c=[4,7,'college,''muskan',8.9,3.5,7.9]
print(c[4])

d=['abc','xyz',5.4,4.9,8.3]
print(d[1])

e=['anjali','sanjana','isha',89,9.6]
print(e[3])

a=[1,2,3,4,5,6,'anita',8.7,7.8,'isha']
print(a[2:7:2])

b=['abc','xyz',2.8,8,7,'lakshita',689,7.3]
print(b[1:5:2])

c=[1,2,4,7.9,8.9,'school','guava','regex',5,8,9]
print(c[3:9:3])

d=[4.5,6.7,4,6,8,2.3,4.5,9,4.5,6.7]
print(d[1:8:2])